FROM jonathancosme/root-jpy-prox

RUN mamba install -c conda-forge mlflow -y && \
    mamba clean --all -f -y

RUN sudo apt-get update && \
    sudo apt-get install -y git

COPY jupyter_server_config.py /etc/jupyter/

