apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: runaiconfigs.run.ai
spec:
  group: run.ai
  names:
    kind: RunaiConfig
    listKind: RunaiConfigList
    plural: runaiconfigs
    singular: runaiconfig
  scope: Namespaced
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          x-kubernetes-preserve-unknown-fields: true

---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
    name: runaijobs.run.ai
spec:
    group: run.ai
    scope: Namespaced
    names:
        plural:  runaijobs
        singular: runaijob
        kind: RunaiJob
        shortNames:
        - rj
    versions:
        -   name: v1
            served: true
            storage: true
            schema:
                openAPIV3Schema:
                    type: object
                    x-kubernetes-preserve-unknown-fields: true
---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: projects.run.ai
spec:
  group: run.ai
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          x-kubernetes-preserve-unknown-fields: true
          properties:
            apiVersion:
              type: string
            kind:
              type: string
            metadata:
              type: object
            spec:
              properties:
                department:
                  type: string
                deservedGpus:
                  format: float
                  type: number
                gpuOverQuotaWeight:
                  format: int32
                  type: number
                maxAllowedGpus:
                  format: float
                  type: number
                permissions:
                  type: object
                  properties:
                    users:
                      items:
                        type: string
                      type: array
                    groups:
                      items:
                        type: string
                      type: array
                interactiveJobTimeLimitSecs:
                  format: int64
                  type: integer
                nodeAffinityInteractive:
                  items:
                    type:
                      string
                  type: array
                nodeAffinityTrain:
                  items:
                    type:
                      string
                  type: array
                swapEnabled:
                  type: boolean
              type: object
          type: object
  scope: Cluster
  names:
    kind: Project
    plural: projects
    singular: project
    shortNames:
      - rp
---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: departments.scheduling.run.ai
spec:
  group: scheduling.run.ai
  names:
    kind: Department
    plural: departments
  scope: Cluster
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          properties:
            apiVersion:
              type: string
            kind:
              type: string
            metadata:
              type: object
            spec:
              properties:
                deservedGpus:
                  format: float
                  type: number
                gpuOverQuotaWeight:
                  format: int32
                  type: number
                maxAllowedGpus:
                  format: float
                  type: number
              type: object
          type: object
---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: podgroups.scheduling.run.ai
spec:
  group: scheduling.run.ai
  names:
    kind: PodGroup
    plural: podgroups
  scope: Namespaced
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          properties:
            apiVersion:
              type: string
            kind:
              type: string
            metadata:
              type: object
            spec:
              properties:
                minMember:
                  format: int32
                  type: integer
                queue:
                  type: string
                priorityClassName:
                  type: string
              type: object
            status:
              properties:
                succeeded:
                  format: int32
                  type: integer
                failed:
                  format: int32
                  type: integer
                running:
                  format: int32
                  type: integer
              type: object
          type: object
---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: queues.scheduling.run.ai
spec:
  group: scheduling.run.ai
  names:
    kind: Queue
    plural: queues
  scope: Cluster
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          properties:
            apiVersion:
              type: string
            kind:
              type: string
            metadata:
              type: object
            spec:
              properties:
                department:
                  type: string
                deservedGpus:
                  format: float
                  type: number
                gpuOverQuotaWeight:
                  format: int32
                  type: number
                maxAllowedGpus:
                  format: float
                  type: number
                interactiveJobTimeLimitSecs:
                  format: int64
                  type: integer
                nodeAffinityInteractive:
                  items:
                    type:
                      string
                  type: array
                nodeAffinityTrain:
                  items:
                    type:
                      string
                  type: array
                swapEnabled:
                  type: boolean
              type: object
          type: object
