kind: SecurityContextConstraints
apiVersion: v1
metadata:
  name: runai-user-job
allowHostDirVolumePlugin: true
priority: 10
runAsUser:
  type: RunAsAny
seLinuxContext:
  type: MustRunAs	
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: runai-user-job
rules:
- apiGroups:
  - security.openshift.io
  resourceNames:
  - runai-user-job
  resources:
  - securitycontextconstraints
  verbs:
  - use
---
apiVersion: security.openshift.io/v1
kind: SecurityContextConstraints
metadata:
  name: runai-container-toolkit
allowHostDirVolumePlugin: true
allowPrivilegeEscalation: true
allowPrivilegedContainer: true
allowedCapabilities:
- '*'
priority: 10
runAsUser:
  type: RunAsAny
seLinuxContext:
  type: RunAsAny
